### ISSUE TITLE
Kraken2 PlusPFP .tar.gz file missing

### ISSUE THREAD

**Issue by mpnelsen** [BenLangmead/aws-indexes#10]
Hi,

I'm trying to download the Kraken2 PlusPFP index from the aws-indexes page and it seems like the file might be missing.  Any suggestions on how to acquire it?  I've tried:

wget https://genome-idx.s3.amazonaws.com/kraken/k2_pluspfp_8gb_20220607.tar.gz
--2022-06-11 11:03:08--  https://genome-idx.s3.amazonaws.com/kraken/k2_pluspfp_8gb_20220607.tar.gz
Resolving genome-idx.s3.amazonaws.com (genome-idx.s3.amazonaws.com)... 52.217.203.105
Connecting to genome-idx.s3.amazonaws.com (genome-idx.s3.amazonaws.com)|52.217.203.105|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-06-11 11:03:09 ERROR 404: Not Found.

And then if I instead click on the .tar.gz hyperlink, it does this (others will download, but this specific index seems problematic):

NoSuchKeyThe specified key does not exist.kraken/k2_pluspfp_8gb_20220607.tar.gzSM1HBSCHZ7ENABCPojxu+b1woEAMK5ME0bk5lcxbdTSf0ROcY/WdzpPbjJFLpssyutdpRTO5+XkxFHDM9s1SuK3FOPM=

Thanks a lot for your help!

**Comment by dkarig** [comment]
I noticed a few issues as well for the latest Kraken2 PlusPFP index:

1) The link appears to point to the 8GB database instead of the full PlusPFP database.  I took a guess and used the following:
`wget https://genome-idx.s3.amazonaws.com/kraken/k2_pluspfp_20220607.tar.gz`

2)  The archive size is 55GB as reported.  I get the same 'inspect' data.  However, the expanded size is 64GB, not 129GB as reported.  

Was there perhaps an intent to create a database capped at 64GB?  The 2021 PlusPFP database was larger.  

Thanks!

**Comment by BenLangmead** [comment]
Thank you -- I think the link issues are now fixed, but I am still looking into what happened with the small archive size for PlusPFP.  I suspect it may contain a truncated version of hash.k2d.  Will report back.

**Comment by BenLangmead** [comment]
(The URL that you guessed is the correct one, but currently points to the suspicious tar archive.)

**Comment by BenLangmead** [comment]
I believe everything is fine with the PFP tar archive.  When I downloaded it and untarred it, I found the expected files with the expected sizes, including the 129 GB `hash.k2d` file:

```
$ ls -lh
total 129G
-rw-r--r-- 1 ben_langmead users 438K May 15 15:23 database100mers.kmer_distrib
-rw-r--r-- 1 ben_langmead users 434K May 15 15:29 database150mers.kmer_distrib
-rw-r--r-- 1 ben_langmead users 431K May 15 15:37 database200mers.kmer_distrib
-rw-r--r-- 1 ben_langmead users 427K May 15 15:45 database250mers.kmer_distrib
-rw-r--r-- 1 ben_langmead users 423K May 15 15:55 database300mers.kmer_distrib
-rw-r--r-- 1 ben_langmead users 445K May 15 15:19 database75mers.kmer_distrib
-rw-r--r-- 1 ben_langmead users 129G May 15 14:43 hash.k2d
-rw-r--r-- 1 ben_langmead users 2.5M Jun  8 08:57 inspect.txt
-rw-r--r-- 1 ben_langmead users   64 May 15 14:43 opts.k2d
-rw-r--r-- 1 ben_langmead users 4.8M May 14 08:27 seqid2taxid.map
-rw-r--r-- 1 ben_langmead users 2.9M May 15 05:29 taxo.k2d
```

Let us know if this is not what you find.

**Comment by dkarig** [comment]
The files look correct on my end, and `kraken2-inspect` and `diff` indicate a match with the provided inspect.txt.
I was thrown off by what must be an issue on our cluster -- `du` and `ls` are returning incorrect summaries, but the individual files and everything else check out.  My apologies for the confusion, and thank you for sharing this resource!

```
(base) [dkarig@node1937 k2_pluspfp_20220607]$ ls -lh
total 64G
-rw-r--r-- 1 dkarig cuuser 438K May 15 15:23 database100mers.kmer_distrib
-rw-r--r-- 1 dkarig cuuser 434K May 15 15:29 database150mers.kmer_distrib
-rw-r--r-- 1 dkarig cuuser 431K May 15 15:37 database200mers.kmer_distrib
-rw-r--r-- 1 dkarig cuuser 427K May 15 15:45 database250mers.kmer_distrib
-rw-r--r-- 1 dkarig cuuser 423K May 15 15:55 database300mers.kmer_distrib
-rw-r--r-- 1 dkarig cuuser 445K May 15 15:19 database75mers.kmer_distrib
-rw-r--r-- 1 dkarig cuuser 129G May 15 14:43 hash.k2d
-rw-r--r-- 1 dkarig cuuser 2.5M Jun  8 08:57 inspect.txt
-rw-r--r-- 1 dkarig cuuser   64 May 15 14:43 opts.k2d
-rw-r--r-- 1 dkarig cuuser 4.8M May 14 08:27 seqid2taxid.map
-rw-r--r-- 1 dkarig cuuser 2.9M May 15 05:29 taxo.k2d
(base) [dkarig@node1937 k2_pluspfp_20220607]$ du -hs
64G    .
(base) [dkarig@node1937 k2_pluspfp_20220607]$ du
66114463      .
```

**Comment by mpnelsen** [comment]
Thx so much, @BenLangmead  and @dkarig!  Very much appreciated.
