### ISSUE TITLE
Individual Kraken2 databases

### ISSUE THREAD

**Issue by zeus19900814** [BenLangmead/aws-indexes#11]
Hi there,

I'm interested in the Kraken2 standard database that can be downloaded here: https://genome-idx.s3.amazonaws.com/kraken/k2_standard_20220607.tar.gz. But it seems too huge to me because it has archaea, bacteria, viral, plasmid, human, etc. databases in it.

Are there individual databases that are available for download? Or can I filter, maybe only human, out of the "full" database? 

Any advise will be helpful!

Thank you,
Zheng

**Comment by tonyjhlam** [comment]
@zeus19900814 If you are having resource limitations, I would suggest you use the minikraken databases found here: https://ccb.jhu.edu/software/kraken2/index.shtml?t=downloads 

They are specifically built for those who have limited computing capacities and those who are unable to load the full Kraken database. You will lose a bit of accuracy and precision (https://ccb.jhu.edu/software/kraken2/images/Kraken1v2_BuildDBAccuracy_Table.png) , but it is less resource intensive.

**Comment by BenLangmead** [comment]
I agree with this suggestion.  Thanks, Tony.
