### ISSUE TITLE
wrong URL for Fruitfly / BDGP6

### ISSUE THREAD

**Issue by qifei9** [BenLangmead/aws-indexes#13]
in the webpage https://benlangmead.github.io/aws-indexes/bowtie, the URL for Fruitfly / BDGP6  ensembl is https://www.ncbi.nlm.nih.gov/assembly/GCF_000002035.5/   which points to the page of GRCz10

**Comment by BenLangmead** [comment]
Thank you!  Just fixed: https://github.com/BenLangmead/aws-indexes/commit/8a04d83a9d54edd627346786e4d034f57043188b
