### ISSUE TITLE
Missing file in kraken2 nt database

### ISSUE THREAD

**Issue by SumeetTiwari07** [BenLangmead/aws-indexes#15]
Hi,
I have downloaded the latest nt database. But the database missing `database150mers.kmer_distrib` file.

**Comment by BenLangmead** [comment]
I see!  I will fix this imminently...

**Comment by BenLangmead** [comment]
this is now fixed.  This file is updated:
https://genome-idx.s3.amazonaws.com/kraken/k2_nt_20230502.tar.gz

And the missing file is also available here, if you'd like to just download that:
https://genome-idx.s3.amazonaws.com/kraken/nt_20230502/database150mers.kmer_distrib

**Comment by SumeetTiwari07** [comment]
Thank you so much.
