### ISSUE TITLE
Modify time for one PlusPFP file seems old

### ISSUE THREAD

**Issue by shreyaramachandran** [BenLangmead/aws-indexes#16]
Hello! Thank you so much for this really valuable service!

I just download the newest PlusPFP database from June 5, and when inspecting the files noticed that one file (database50mers.kmer_distrib) appears to have last been modified a couple months before the rest of them? I just wanted to confirm that's the correct version of the file before using it for analysis, just in case it's an older version. Thank you so much!

![k2](https://github.com/BenLangmead/aws-indexes/assets/42902421/fc669a16-3d5b-4181-a181-06519e415990)

**Comment by BenLangmead** [comment]
Thank you for catching this.  We have replaced the file (database50mers...) and the tarball both so that they now include the correct, up-to-date database.
