### ISSUE TITLE
Please provide viral-only database

### ISSUE THREAD

**Issue by pvanheus** [BenLangmead/aws-indexes#2]
Hi there

In the context of SARS-CoV-2 sequencing, a viral-only database is useful in analysing the content of a sequencing run, e.g. the approach used in [covid-19-signal](https://github.com/jaleezyy/covid-19-signal). Could you please add this viral-only DB to the ones that you distributed as [building it](https://github.com/jaleezyy/covid-19-signal/blob/master/scripts/get_data_dependencies.sh#L54) locally is painfully slow.

Thanks

**Comment by BenLangmead** [comment]
Thanks for the suggestion.  I will plan to do this when I make updated databases this month

**Comment by BenLangmead** [comment]
New indexes posted today (dated 12/2 because that's when I download the libraries) include a Viral database.  Please let us know if you have any issues: https://benlangmead.github.io/aws-indexes/k2 (you may have to reload page once or twice to get latest version)
