### ISSUE TITLE
nt Database is missing ktaxonomy.tsv?

### ISSUE THREAD

**Issue by Ge0rges** [BenLangmead/aws-indexes#23]
Downloaded and decompressed twice to make sure, but it seems like the `nt Database` is missing the `ktaxonomy.tsv` produced by `make_ktaxonomy.py` script from [KrakenTools](https://github.com/jenniferlu717/KrakenTools). The footer indicates this should be present. Have I missed it somehow?

**Comment by ohickl** [comment]
same here

**Comment by varshamathur1** [comment]
Hey! Also looking for the ktaxonomy.tsv file! Any updates on this?

**Comment by ch4rr0** [comment]
Hello,

I am not sure why the file is missing from prior database builds as we have since purged those builds from our servers. I can assure you that it will be available in the upcoming build which is currently underway. 

Apologies for any inconvenience caused.
