### ISSUE TITLE
Timeline estimate for next edition of the pre-built databases?

### ISSUE THREAD

**Issue by jeffkaufman** [BenLangmead/aws-indexes#29]
It looks like the most recent pre-built databases are from 2024-01-12, and in the past there's often been new ones in the early summer (2023-06-05, 2022-06-07, 2021-05-17).  Do you have an estimate of when the next round of pre-built databases will be out?

(Not trying to rush you!  I have some data I ran through the 2022-12-09 version. I'd like to bring it up to date, but if there's likely going to be a new version I'll wait for that to land first.)

**Comment by BenLangmead** [comment]
You are correct that we are behind on what should have been an April/May release.  We will get started now with the goal of releasing in a couple weeks in early June.  Thank you for this reminder.

**Comment by jeffkaufman** [comment]
Thanks!  Looking forward to it!

**Comment by BenLangmead** [comment]
OK, they're up there now.  A new nt (as of May, 2024) is not quite up there yet but coming soon.
