### ISSUE TITLE
Persistent URLs 

### ISSUE THREAD

**Issue by zoey-rw** [BenLangmead/aws-indexes#3]
I'm wondering if the URL for a specific database version, say the 9/19/2020 version, will remain valid after a newer update is posted - or, if the old URL will instead redirect to the newer version, or break completely? Just trying to plan ahead. Thanks for providing these databases!

**Comment by BenLangmead** [comment]
I do plan to keep the old URLs in perpetuity, yes.  Where "perpetuity" is unavoidably a function of how long AWS wants to support our bucket
