### ISSUE TITLE
persistent tar structure kraken2/bracken

### ISSUE THREAD

**Issue by angelovangel** [BenLangmead/aws-indexes#5]
In contrast to previous kraken2 database archives, e.g. on `ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/`, now the archives do not have a leading directory. Provided kraken2 takes a directory name as an argument, it is I think better to keep the leading directory in the tar archive, so that it is ready to use after `tar -xf ...`
I guess this is going to break a lot of scripts (mine too of course)...
Apart from that, thanks for this repo and the efforts to put the indexes up on aws!

**Comment by BenLangmead** [comment]
Thanks.  It is unfortunate that this broke existing scripts, I agree.  But given the current situation, I think the right way forward for these indexes is to continue with the same policy
